apiVersion: boom.caos.ch/v1beta1
kind: Toolset
metadata:
  name: caos
  namespace: caos-system
spec:
  currentStatePath: caos-internal/boom
  preApply:
    deploy: false
    folder: preapply
  postApply:
    deploy: false
    folder: postapply
  prometheus-operator:
    deploy: true
  logging-operator:
    deploy: true
  prometheus-node-exporter:
    deploy: true
  grafana:
    deploy: true
  ambassador:
    deploy: true
    service:
      type: LoadBalancer
  kube-state-metrics:
    deploy: true
  argocd:
    deploy: false
    customImage:
      enabled: false
      imagePullSecret: github-image
      gopassStores:
      - directory: directory
        storeName: store
        sshKey:
          name: "argocd-ssh-config"
          key: "ssh-boom-test"
          internalName: "ssh-identity"
        gpgKey: 
          name: "argocd-gpg-keys"
          key: "gpg-boom-test"
          internalName: "gpg-identity"
    repositories:
    - name: boom-test-ops
      url: git@github.com:tribock/boom-test-ops.git
      certificateSecret:
        name: boom-test-ops
        key: ops-ssh
  prometheus:
    deploy: true
    # storage:
    #   size: 5Gi
    #   storageClass: standard
  loki:
    deploy: true
    clusterOutput: true
    # storage:
    #   size: 5Gi
    #   storageClass: standard

